http:
  routers:
    flotodor-router:
      rule: "PathPrefix(`/`) && !PathPrefix(`/dashboard`) && !PathPrefix(`/api`)"
      entryPoints:
        - web
      service: flotodor-service

    traefik-dashboard:
      rule: "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      entryPoints:
        - traefik
      service: api@internal
      middlewares:
        - auth

  middlewares:
    auth:
      basicAuth:
        users:
          - "flotodor:$2y$05$x/9oT3Amok6W8YXmto5HXOyhxQ5uEoMdqBd.Er2NkTITeQpToj1b."

  services:
    flotodor-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.10.2"
          - url: "http://192.168.10.3"
          - url: "http://192.168.10.4"
          - url: "http://192.168.10.5"
          - url: "http://192.168.10.6"
          - url: "http://192.168.10.7"
          - url: "http://192.168.10.8"
          - url: "http://192.168.10.9"


