entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: false

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: DEBUG
